#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the 'reverseArray' function below.
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY a as parameter.

def reverseArray(a):
    return a[::-1]

if __name__ == '__main__':
    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))

    result = reverseArray(arr)

    print(*result)
